import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: 'index.html',
        bookwiseproject: 'html/bookwiseproject.html',
        budgetproject: 'html/budgetproject.html',
        coffeeproject: 'html/coffeeproject.html',
        connect: 'html/connect.html',
        projects: 'html/projects.html',
        'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Added': 'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Added.png',
        'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-BooksList': 'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-BooksList.png',
        'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Cart': 'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Cart.png',
        'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Home': 'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Home.png',
        'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Login': 'assets/images/Bookstore-SpringBoot/Bookstore-SpringBoot-Login.png',
        'assets/images/Budget-Master-UI/Add Expense': 'assets/images/Budget-Master-UI/Add Expense.png',
        'assets/images/Budget-Master-UI/Bill Details': 'assets/images/Budget-Master-UI/Bill Details.png',
        'assets/images/Budget-Master-UI/Bill Payment': 'assets/images/Budget-Master-UI/Bill Payment.png',
        'assets/images/Budget-Master-UI/Connecting Wallet': 'assets/images/Budget-Master-UI/Connecting Wallet.png',
        'assets/images/Budget-Master-UI/Expense Tracking': 'assets/images/Budget-Master-UI/Expense Tracking.png',
        'assets/images/Budget-Master-UI/Homepage': 'assets/images/Budget-Master-UI/Homepage.png',
        'assets/images/Budget-Master-UI/Income Transactions': 'assets/images/Budget-Master-UI/Income Transactions.png',
        'assets/images/Budget-Master-UI/Invoice': 'assets/images/Budget-Master-UI/Invoice.png',
        'assets/images/Budget-Master-UI/Notification Screen': 'assets/images/Budget-Master-UI/Notification Screen.png',
        'assets/images/Budget-Master-UI/Opening Screen': 'assets/images/Budget-Master-UI/Opening Screen.png',
        'assets/images/Budget-Master-UI/Personal Profile': 'assets/images/Budget-Master-UI/Personal Profile.png',
        'assets/images/Budget-Master-UI/Profile': 'assets/images/Budget-Master-UI/Profile.png',
        'assets/images/Budget-Master-UI/Security': 'assets/images/Budget-Master-UI/Security.png',
        'assets/images/Budget-Master-UI/Template': 'assets/images/Budget-Master-UI/Template.pdf',
        'assets/images/Budget-Master-UI/Under Construction': 'assets/images/Budget-Master-UI/Under Construction.png',
        'assets/images/Budget-Master-UI/Wallet': 'assets/images/Budget-Master-UI/Wallet.png',
        'assets/images/Coffee-Express-FX/Coffee-Express-FX-Billing': 'assets/images/Coffee-Express-FX/Coffee-Express-FX-Billing.png',
        'assets/images/Coffee-Express-FX/Coffee-Express-FX-Login': 'assets/images/Coffee-Express-FX/Coffee-Express-FX-Login.png',
        'assets/images/Coffee-Express-FX/Coffee-Express-FX-Order': 'assets/images/Coffee-Express-FX/Coffee-Express-FX-Order.png',
        'assets/images/Coffee-Express-FX/Coffee-Express-FX-Receipt': 'assets/images/Coffee-Express-FX/Coffee-Express-FX-Receipt.png',
        'assets/images/Coffee-Express-FX/Coffee-Express-FX-Signup': 'assets/images/Coffee-Express-FX/Coffee-Express-FX-Signup.png',
        'assets/images/BG-Connect-Dark': 'assets/images/BG-Connect-Dark.jpg',
        'assets/images/BG-Home-Dark': 'assets/images/BG-Home-Dark.jpg',
        'assets/images/BG-Projects-Dark': 'assets/images/BG-Projects-Dark.jpg',
        'assets/images/Bookstore-Showcase-SB': 'assets/images/Bookstore-Showcase-SB.png',
        'assets/images/Budget-Master-Showcase': 'assets/images/Budget-Master-Showcase.png',
        'assets/images/Coffee-Express-Showcase': 'assets/images/Coffee-Express-Showcase.png',
        'assets/images/Connect-Picture': 'assets/images/Connect-Picture.jpg',
        'assets/images/Profile-Picture': 'assets/images/Profile-Picture.jpg',
        'css/bookwisemobile': 'css/bookwisemobile.css',
        'css/budgetmobile': 'css/budgetmobile.css',
        'css/coffeemobile': 'css/coffeemobile.css',
        'css/global': 'css/global.css',
        'js/index': 'js/index.js',
      },
    },
  },
});
